package com.it.academy.gk.sc0.statements;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * This class contains unit tests for the PrintNumbers class.
 */
@DisplayName("Print Numbers Test")
class PrintNumbersTest {
    /**
     * An instance of the PrintNumbers class, used to test its methods.
     */
    private PrintNumbers printNumbers;

    /**
     * This method provides test cases for the testGenerateNumbersTask1 method.
     * Each test case consists of three arguments: the start value, the end value, and the expected result.
     * The expected result is a string
     * representing the numbers that should be generated by the generateNumbersTask1 method.
     */
    @SuppressFBWarnings("NP_NONNULL_RETURN_VIOLATION")
    @Contract(pure = true)
    static @NotNull Stream<Arguments> generateNumbersTask1Provider() {
        return Stream.of(
                Arguments.of(1, 7, "1 2 3 4 5 6 7 "),
                Arguments.of(0, 0, "0 "),
                Arguments.of(-3, 3, "-3 -2 -1 0 1 2 3 ")
        );
    }

    /**
     * This method provides test cases for the testGenerateNumbersTask2 method.
     * Each test case consists of four arguments: the first value,
     * the last value, the increment value, and the expected result.
     * The expected result is a string
     * representing the numbers that should be generated by the generateNumbersTask2 method.
     */
    @SuppressFBWarnings("NP_NONNULL_RETURN_VIOLATION")
    @Contract(pure = true)
    static @NotNull Stream<Arguments> generateNumbersTask2Provider() {
        return Stream.of(
                Arguments.of(100, 10, -10, "100 90 80 70 60 50 40 30 20 10 "),
                Arguments.of(100, 100, -10, "100 "),
                Arguments.of(-30, -70, -10, "-30 -40 -50 -60 -70 ")
        );
    }

    /**
     * This method provides test cases for the testPrintNumbersTask4 method.
     * Each test case consists of three arguments: the upper bound, the lower bound, and the expected result.
     * The expected result is a string representing the numbers that should be printed by the printNumbersTask4 method.
     */
    @SuppressFBWarnings("NP_NONNULL_RETURN_VIOLATION")
    @Contract(pure = true)
    static @NotNull Stream<Arguments> printNumbersTask4Provider() {
        return Stream.of(
                Arguments.of(3, -3, "3 2 1 0 -1 -2 -3 "),
                Arguments.of(0, 0, "0 "),
                Arguments.of(-3, 3, "")
        );
    }

    /**
     * This method provides test cases for the testPrintNumbersTask1 method.
     * Each test case consists of three arguments: the minimum value, the maximum value, and the expected result.
     * The expected result is a string representing the numbers that should be printed by the printNumbersTask1 method.
     */
    @SuppressFBWarnings("NP_NONNULL_RETURN_VIOLATION")
    @Contract(pure = true)
    static @NotNull Stream<Arguments> printNumbersTask1Provider() {
        return Stream.of(
                Arguments.of(1, 5, "1 2 3 4 5 "),
                Arguments.of(5, 5, "5 "),
                Arguments.of(-5, -1, "-5 -4 -3 -2 -1 ")
        );
    }

    /**
     * This method provides test cases for the testPrintNumbersTask2 method.
     * Each test case consists of three arguments: the beginning value, the finish value, and the expected result.
     * The expected result is a string representing the numbers that should be printed by the printNumbersTask2 method.
     */
    @SuppressFBWarnings("NP_NONNULL_RETURN_VIOLATION")
    @Contract(pure = true)
    static @NotNull Stream<Arguments> printNumbersTask2Provider() {
        return Stream.of(
                Arguments.of(5, 1, "5 4 3 2 1 "),
                Arguments.of(5, 5, "5 "),
                Arguments.of(-5, -9, "-5 -6 -7 -8 -9 ")
        );
    }

    /**
     * This method is run before each test method, ensuring that each test has a fresh instance
     * of the PrintNumbers class to work with.
     */
    @BeforeEach
    void setUp() {
        printNumbers = new PrintNumbers();
    }

    /**
     * This method tests the generateNumbersTask1 method of the PrintNumbers class.
     * It takes three arguments: the start value, the end value, and the expected result.
     * The expected result is a string representing the numbers that should be generated
     * by the generateNumbersTask1 method. The method calls the generateNumbersTask1 method
     * with the specified start and end values and compares the result to the expected result.
     */
    @ParameterizedTest(name = "generateNumbersTask1({0}, {1}) = {2}")
    @MethodSource("generateNumbersTask1Provider")
    @DisplayName("Test generateNumbersTask1 method")
    void testGenerateNumbersTask1(final int start, final int end, final String expected) {
        String actual = printNumbers.generateNumbersTask1(start, end);

        assertEquals(expected, actual);
    }

    /**
     * This method tests the generateNumbersTask2 method of the PrintNumbers class.
     * It takes four arguments: the first value, the last value, the increment value, and the expected result.
     * The expected result is a string representing the numbers that should be generated
     * by the generateNumbersTask2 method.
     * The method calls the generateNumbersTask2 method with the specified first value,
     * last value and increment value and compares the result to the expected result.
     */
    @ParameterizedTest(name = "generateNumbersTask2({0}, {1}, {2}) = {3}")
    @MethodSource("generateNumbersTask2Provider")
    @DisplayName("Test generateNumbersTask2 method")
    void testGenerateNumbersTask2(final int first, final int last, final int increment, final String expected) {
        String actual = printNumbers.generateNumbersTask2(first, last, increment);

        assertEquals(expected, actual);
    }

    /**
     * This method tests the printNumbersTask4 method of the PrintNumbers class.
     * It takes three arguments: the upper bound, the lower bound, and the expected result.
     * The expected result is a string representing the numbers that should be printed by the printNumbersTask4 method.
     * The method calls the printNumbersTask4 method with the specified upper and lower bounds
     * and compares the result to the expected result.
     */
    @ParameterizedTest(name = "PrintNumbersTask4({0}, {1}) = {2}")
    @MethodSource("printNumbersTask4Provider")
    @DisplayName("Test printNumbersTask4 method")
    void testPrintNumbersTask4(final int upperBound, final int lowerBound, final String expected) {
        String actual = printNumbers.printNumbersTask4(upperBound, lowerBound);

        assertEquals(expected, actual);
    }

    /**
     * This method tests the printNumbersTask1 method of the PrintNumbers class.
     * It takes three arguments: the minimum value, the maximum value, and the expected result.
     * The expected result is a string representing the numbers that should be printed by the printNumbersTask1 method.
     * The method calls the printNumbersTask1 method with the specified minimum and maximum values and compares
     * the result to the expected result.
     */
    @ParameterizedTest(name = "printNumbersTask1({0}, {1}) = {2}")
    @MethodSource("printNumbersTask1Provider")
    @DisplayName("Test printNumbersTask1 method")
    void testPrintNumbersTask1(final int minValue, final int maxValue, final String expected) {
        String actual = printNumbers.printNumbersTask1(minValue, maxValue);

        assertEquals(expected, actual);
    }

    /**
     * This method tests the printNumbersTask2 method of the PrintNumbers class.
     * It takes three arguments: the beginning value, the finish value, and the expected result.
     * The expected result is a string representing the numbers that should be printed by the printNumbersTask2 method.
     * The method calls the printNumbersTask2 method with the specified beginning and finish values and compares
     * the result to the expected result.
     */
    @ParameterizedTest(name = "printNumbersTask2({0}, {1}) = {2}")
    @MethodSource("printNumbersTask2Provider")
    @DisplayName("Test printNumbersTask2 method")
    void testPrintNumbersTask2(final int begin, final int finish, final String expected) {
        String actual = printNumbers.printNumbersTask2(begin, finish);

        assertEquals(expected, actual);
    }
}
